dist: xenial
language: python
python:
  - "3.7"
deploy:
  provider: pypi
  user: adamrehn
  distributions: bdist_wheel
  on:
    tags: true
  password:
    secure: On10RovRYLb2S9TmoqzHCnHF1Bld5UJSbnoMCWytjwXKtp/+FphcT5htSNBKUpoBbjxdCT0we0Vy1GtGJi8auNZa+fhcegIikXVDg5iBn2UvgLVWrWZBQWDPCjkdL7fCij5MSAjJxBEuYRcfeGTM76wyYfYaO4omvNE96CVoWmkD3Ev0h1wrxeUoy7mAQ7Qy/46gaQ73LH0YnhaZ1s5frtESkoFsfqNwkrFY14Iu2gfnDZB6WDVqS00oOXhjiAjEyyGfCk6eW4GyUdVa2dWaapHDVeruvr6ICBj5DOXpf37dsIZvjqpWAqO76+4rbJ8tyPkjsr+DyQ2hq7a1Lq+TWlVLh78FkVoQATDRy/Y1Ai+X/nhnFkNrrIHHaS1B82Cnyq2XWLp/iUoxAZLTP7q11L4vrpOccSx8Ed5LaPoucTNvEVyM//eD8J8Z12OCue+ZAmWdq1E1slkfeBcp0bAkfTQ/9K0HJ7t0fCUj3+Y4DbSLB3H7zT0Ev6+roZWHzcwPf1Wct+Qwe2RdTZRdAt0C/tdSCTgB82/GrUWnaKLO4f2Flyr2BOUFMZDnOYR5MOs9826n8RnDz9mXDSqEZWOy01jjMS7H7jvKBQQwbVllpfxZqkd+JXumsf7k2l4nV3ETIQuU4NYExoTSe+Y32zP8Zgbe+Y9V0kte8a4m9FO7HvI=
